name: Playwright tests triggered manually
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Создаем Docker image
    - name: Build Docker image 
      run: docker build -t playwright-tests -f Dockerfile.custom .
    # Запуск Docker контейнера и запуск тестов в нем
    - name: Run Docker container with Playwright tests
      run: docker run playwright-tests
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
