name: Playwright Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Создаем Docker image
      - name: Build Docker image using official image
        run: docker build -t plw-tests -f Dockerfile.official .
      # Запуск Docker контейнера и запуск тестов в нем
      - name: Run Docker container with Playwright tests
        run: docker run -v ${{ github.workspace }}/playwright-report:/usr/src/app/playwright-report plw-tests
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
